name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -p:PublishProfile=FolderProfile
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Digiruokalista
        path: /home/runner/work/Digiruokalista.com/Digiruokalista.com/Ruokalistat.tk/bin/Debug/net6.0/publish/
